import { Link } from 'react-router-dom';
import { Building2, FileText, Key, LogIn, ArrowRight, Shield, Zap } from 'lucide-react';
import Reveal from '../../components/ui/Reveal';

const steps = [
  { icon: Building2, title: 'Onboarding', desc: 'Register your institution and set up your organization profile in minutes.' },
  { icon: FileText, title: 'Create Exam', desc: 'Teachers build question banks, set time limits, and configure anti-cheating settings.' },
  { icon: Key, title: 'Get X-Code', desc: 'The system generates a unique, secure, single-use examination access code.' },
  { icon: LogIn, title: 'Enter & Take Exam', desc: 'Students enter the X-Code and complete the exam in a secure, proctored environment.' },
];

const xcodeSegments = [
  { label: 'Prefix', value: 'PV', desc: 'Procto Vision identifier' },
  { label: 'Random', value: '7K4M', desc: 'Unique exam hash' },
  { label: 'Checksum', value: '82QX', desc: 'Validation code' },
];

const faqs = [
  { q: 'What is an X-Code?', a: 'An X-Code is a unique examination access code generated by Procto Vision for each exam session. It ensures only authorized students can access specific examinations within the designated time window.' },
  { q: 'How long is an X-Code valid?', a: 'X-Code validity is set by the teacher when creating the exam. It can be configured for a specific date range and time window, after which it expires automatically.' },
  { q: 'Can an X-Code be reused?', a: 'No. Each X-Code is designed for single-use per student. Once a student uses an X-Code to enter an exam, it cannot be used again by anyone.' },
  { q: 'How do students receive their X-Code?', a: "Teachers share the X-Code with students through their institution's communication channels — email, WhatsApp, notice board, or any preferred method." },
];

export default function HowItWorks() {
  return (
    <>
      <section className="hero">
        <div className="hero-glow" />
        <div className="container">
          <Reveal className="hero-content text-center mx-auto">
            <p className="caption" style={{ marginBottom: 12 }}>
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Zap size={12} /> Simple Process</span>
            </p>
            <h1 className="headline-super hero-title">
              How it works.
            </h1>
            <p className="hero-subtitle">
              From institution setup to exam completion — a streamlined process
              that makes secure online examinations effortless.
            </p>
            <div className="hero-actions">
              <Link to="/platform" className="btn btn-primary">
                Explore Platform <ArrowRight size={16} />
              </Link>
              <Link to="/pricing" className="btn btn-secondary">
                View Pricing
              </Link>
            </div>
          </Reveal>
        </div>
      </section>

      <section className="section section-gray">
        <div className="container text-center">
          <Reveal>
            <p className="caption" style={{ marginBottom: 8 }}>Step by Step</p>
            <h2 className="headline-large">
              Four steps to secure examinations.
            </h2>
            <p className="subhead-large" style={{ maxWidth: 520, margin: '0 auto' }}>
              Our process is designed to be intuitive for both educators and students.
            </p>
          </Reveal>
          <Reveal delay={100}>
            <div className="steps-flow" style={{ marginTop: 64 }}>
              {steps.map((step, i) => (
                <div key={step.title} className="step-item">
                  <div className="step-number">{i + 1}</div>
                  <h3>{step.title}</h3>
                  <p>{step.desc}</p>
                </div>
              ))}
            </div>
          </Reveal>
        </div>
      </section>

      <section className="section">
        <div className="container text-center">
          <Reveal>
            <p className="caption" style={{ marginBottom: 8 }}>X-Code System</p>
            <h2 className="headline-large">
              Understanding the X-Code.
            </h2>
            <p className="subhead-large" style={{ maxWidth: 520, margin: '0 auto' }}>
              Each examination access code is uniquely generated and structurally validated.
            </p>
          </Reveal>

          <Reveal delay={100}>
            <div style={{ maxWidth: 640, margin: '48px auto 0' }}>
              <div className="apple-card" style={{ padding: '40px 48px' }}>
                <p className="caption" style={{ marginBottom: 24 }}>Example X-Code Format</p>
                <div className="xcode-segments-row" style={{ display: 'flex', justifyContent: 'center', gap: 12, marginBottom: 32, flexWrap: 'wrap' }}>
                  {xcodeSegments.map((seg, i) => (
                    <div key={seg.label} style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                      <div style={{
                        background: 'var(--bg-dark)',
                        color: 'white',
                        padding: '16px 28px',
                        borderRadius: 12,
                        fontFamily: 'var(--font-mono)',
                        fontSize: '1.8rem',
                        fontWeight: 700,
                        letterSpacing: '0.1em',
                      }}>
                        {seg.value}
                      </div>
                      {i < xcodeSegments.length - 1 && (
                        <span className="xcode-dash" style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>-</span>
                      )}
                    </div>
                  ))}
                </div>
                <div className="xcode-labels-row" style={{ display: 'flex', justifyContent: 'center', gap: 40, flexWrap: 'wrap' }}>
                  {xcodeSegments.map((seg) => (
                    <div key={seg.label} style={{ textAlign: 'center' }}>
                      <p className="caption" style={{ marginBottom: 4 }}>{seg.label}</p>
                      <p className="subhead-medium">{seg.desc}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </Reveal>

          <Reveal delay={200}>
            <div className="apple-card" style={{ maxWidth: 640, margin: '24px auto 0', padding: '20px 24px', display: 'flex', alignItems: 'center', gap: 12, textAlign: 'left' }}>
              <Shield size={18} style={{ color: 'var(--accent)', flexShrink: 0 }} />
              <p className="subhead-medium">
                X-Codes are cryptographically generated and cannot be guessed or brute-forced.
                Each code is validated server-side before granting exam access.
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      <section className="section section-gray">
        <div className="container text-center">
          <Reveal>
            <p className="caption" style={{ marginBottom: 8 }}>FAQ</p>
            <h2 className="headline-large">
              Frequently asked questions.
            </h2>
          </Reveal>
          <div style={{ maxWidth: 640, margin: '48px auto 0', display: 'flex', flexDirection: 'column', gap: 12, textAlign: 'left' }}>
            {faqs.map((faq, i) => (
              <Reveal key={faq.q} delay={i * 60}>
                <div className="apple-card" style={{ padding: '24px 28px' }}>
                  <h3 className="headline-small" style={{ marginBottom: 8 }}>{faq.q}</h3>
                  <p className="subhead-medium">{faq.a}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container text-center">
          <Reveal>
            <h2 className="headline-large">
              Ready to get started?
            </h2>
            <p className="subhead-large" style={{ maxWidth: 480, margin: '12px auto 0' }}>
              Set up your institution and start conducting secure exams today.
            </p>
            <div style={{ display: 'flex', gap: 16, justifyContent: 'center', marginTop: 32 }}>
              <Link to="/signup" className="btn btn-primary">Create Account</Link>
              <Link to="/contact" className="btn btn-secondary">Talk to Sales</Link>
            </div>
          </Reveal>
        </div>
      </section>
    </>
  );
}
