import { Building2, FileText, Key, LogIn, Monitor, ArrowRight, ChevronRight, Shield, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useInView } from '../../hooks/useInView';

const steps = [
  {
    icon: Building2,
    number: '01',
    title: 'Institution Onboarding',
    description: 'Register your institution and set up your organization profile. Configure departments, user roles, and examination policies in minutes.',
    details: ['Create organization account', 'Set up departments', 'Configure user roles', 'Define policies'],
  },
  {
    icon: FileText,
    number: '02',
    title: 'Teacher Creates Exam',
    description: 'Teachers create examinations with question banks, set time limits, define passing criteria, and configure anti-cheating settings.',
    details: ['Build question bank', 'Set exam parameters', 'Configure security', 'Schedule availability'],
  },
  {
    icon: Key,
    number: '03',
    title: 'System Generates X-Code',
    description: 'Upon exam creation, the system generates a unique X-Code — a secure, single-use examination access code for students.',
    details: ['Auto-generated code', 'Unique per exam', 'Time-bound validity', 'One-time use only'],
  },
  {
    icon: LogIn,
    number: '04',
    title: 'Student Enters X-Code',
    description: 'Students receive the X-Code via their institution. They enter it on the Procto Vision portal to access the designated examination.',
    details: ['Visit exam portal', 'Enter X-Code', 'Verify identity', 'Enter exam room'],
  },
  {
    icon: Monitor,
    number: '05',
    title: 'Student Takes Exam',
    description: 'The student completes the examination in a secure, proctored environment. Anti-cheating measures ensure exam integrity throughout.',
    details: ['Secure exam interface', 'Auto-save progress', 'Anti-cheat monitoring', 'Submit & finish'],
  },
];

const xcodeSegments = [
  { label: 'Prefix', value: 'PV', description: 'Procto Vision identifier' },
  { label: 'Random', value: '7K4M', description: 'Unique exam hash' },
  { label: 'Checksum', value: '82QX', description: 'Validation code' },
];

const faqs = [
  {
    q: 'What is an X-Code?',
    a: 'An X-Code is a unique examination access code generated by Procto Vision for each exam session. It ensures that only authorized students can access specific examinations within the designated time window.',
  },
  {
    q: 'How long is an X-Code valid?',
    a: 'X-Code validity is set by the teacher when creating the exam. It can be configured for a specific date range and time window, after which it expires automatically.',
  },
  {
    q: 'Can an X-Code be reused?',
    a: 'No. Each X-Code is designed for single-use per student. Once a student uses an X-Code to enter an exam, it cannot be used again by anyone.',
  },
  {
    q: 'How do students receive their X-Code?',
    a: "Teachers share the X-Code with students through their institution's communication channels — email, WhatsApp, notice board, or any preferred method.",
  },
];

export default function HowItWorks() {
  const { ref: heroRef, isInView: heroVisible } = useInView();
  const { ref: stepsRef, isInView: stepsVisible } = useInView();
  const { ref: xcodeRef, isInView: xcodeVisible } = useInView();
  const { ref: faqRef, isInView: faqVisible } = useInView();
  const { ref: ctaRef, isInView: ctaVisible } = useInView();

  return (
    <>
      {/* Hero */}
      <section className="hero">
        <div className="hero-glow" />
        <div className="container">
          <div ref={heroRef} className={`hero-content reveal ${heroVisible ? 'visible' : ''}`}>
            <span className="hero-badge">
              <Zap size={14} /> Simple Process
            </span>
            <h1 className="heading-xl hero-title">
              How It <span className="gradient-text">Works</span>
            </h1>
            <p className="hero-subtitle">
              From institution setup to exam completion — a streamlined five-step process
              that makes secure online examinations effortless.
            </p>
            <div className="hero-actions">
              <Link to="/platform" className="btn btn-primary btn-lg">
                Explore Platform <ArrowRight size={18} />
              </Link>
              <Link to="/pricing" className="btn btn-secondary btn-lg">
                View Pricing
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Steps */}
      <section className="section section-border">
        <div className="container">
          <div ref={stepsRef} className={`text-center reveal ${stepsVisible ? 'visible' : ''}`} style={{ maxWidth: 640, margin: '0 auto 64px' }}>
            <span className="label">Step by Step</span>
            <h2 className="heading-lg" style={{ marginTop: 12 }}>
              Five Steps to <span className="gradient-text">Secure Examinations</span>
            </h2>
            <p className="body-lg" style={{ marginTop: 12 }}>
              Our process is designed to be intuitive for both educators and students
            </p>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 48 }}>
            {steps.map((step, index) => {
              const Icon = step.icon;
              return (
                <div key={step.number} style={{
                  display: 'grid',
                  gridTemplateColumns: index % 2 === 0 ? '1fr 1.2fr' : '1.2fr 1fr',
                  gap: 48,
                  alignItems: 'center',
                }}>
                  {index % 2 === 1 && (
                    <div style={{ order: 2 }}>
                      <div className="card" style={{ padding: 40, position: 'relative' }}>
                        <span style={{
                          position: 'absolute',
                          top: -16,
                          left: 24,
                          background: 'var(--accent)',
                          color: 'white',
                          padding: '6px 16px',
                          borderRadius: 'var(--radius)',
                          fontSize: '0.8rem',
                          fontWeight: 700,
                          letterSpacing: '0.05em',
                        }}>
                          STEP {step.number}
                        </span>
                        <h3 className="heading-md" style={{ marginTop: 8, marginBottom: 12 }}>{step.title}</h3>
                        <p className="body-md" style={{ marginBottom: 20 }}>{step.description}</p>
                        <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
                          {step.details.map((d) => (
                            <li key={d} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                              <ChevronRight size={14} style={{ color: 'var(--accent-light)' }} />
                              {d}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}
                  {index % 2 === 1 && (
                    <div style={{ order: 1, display: 'flex', justifyContent: 'center' }}>
                      <div style={{
                        width: 160,
                        height: 160,
                        background: 'var(--accent-glow)',
                        borderRadius: '50%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        border: '2px solid rgba(99, 102, 241, 0.2)',
                      }}>
                        <Icon size={64} style={{ color: 'var(--accent-light)' }} />
                      </div>
                    </div>
                  )}
                  {index % 2 === 0 && (
                    <div>
                      <div className="card" style={{ padding: 40 }}>
                        <span style={{
                          display: 'inline-block',
                          background: 'var(--accent)',
                          color: 'white',
                          padding: '6px 16px',
                          borderRadius: 'var(--radius)',
                          fontSize: '0.8rem',
                          fontWeight: 700,
                          letterSpacing: '0.05em',
                          marginBottom: 16,
                        }}>
                          STEP {step.number}
                        </span>
                        <h3 className="heading-md" style={{ marginBottom: 12 }}>{step.title}</h3>
                        <p className="body-md" style={{ marginBottom: 20 }}>{step.description}</p>
                        <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
                          {step.details.map((d) => (
                            <li key={d} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                              <ChevronRight size={14} style={{ color: 'var(--accent-light)' }} />
                              {d}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}
                  {index % 2 === 0 && (
                    <div style={{ display: 'flex', justifyContent: 'center' }}>
                      <div style={{
                        width: 160,
                        height: 160,
                        background: 'var(--accent-glow)',
                        borderRadius: '50%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        border: '2px solid rgba(99, 102, 241, 0.2)',
                      }}>
                        <Icon size={64} style={{ color: 'var(--accent-light)' }} />
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* X-Code Explanation */}
      <section className="section section-border">
        <div className="container">
          <div ref={xcodeRef} className={`text-center reveal ${xcodeVisible ? 'visible' : ''}`} style={{ maxWidth: 640, margin: '0 auto 48px' }}>
            <span className="label">X-Code System</span>
            <h2 className="heading-lg" style={{ marginTop: 12 }}>
              Understanding the <span className="gradient-text">X-Code</span>
            </h2>
            <p className="body-lg" style={{ marginTop: 12 }}>
              Each examination access code is uniquely generated and structurally validated
            </p>
          </div>

          <div className="card" style={{ maxWidth: 700, margin: '0 auto 48px', textAlign: 'center' }}>
            <p className="body-sm" style={{ marginBottom: 20 }}>Example X-Code Format</p>
            <div style={{
              display: 'flex',
              justifyContent: 'center',
              gap: 8,
              marginBottom: 32,
            }}>
              {xcodeSegments.map((seg, i) => (
                <div key={seg.label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <div style={{
                    background: 'var(--bg)',
                    color: 'var(--text-primary)',
                    padding: '16px 24px',
                    borderRadius: 'var(--radius)',
                    fontFamily: "'Courier New', monospace",
                    fontSize: '1.8rem',
                    fontWeight: 800,
                    letterSpacing: '0.1em',
                    minWidth: 80,
                    border: '1px solid var(--border)',
                  }}>
                    {seg.value}
                  </div>
                  {i < xcodeSegments.length - 1 && (
                    <span style={{ fontSize: '1.5rem', color: 'var(--text-muted)', fontWeight: 300 }}>-</span>
                  )}
                </div>
              ))}
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', gap: 32 }}>
              {xcodeSegments.map((seg) => (
                <div key={seg.label} style={{ textAlign: 'center' }}>
                  <span className="label" style={{ fontSize: '0.7rem' }}>{seg.label}</span>
                  <p className="body-sm" style={{ marginTop: 4 }}>{seg.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="xcode-info" style={{ maxWidth: 700, margin: '0 auto' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <Shield size={20} style={{ color: 'var(--accent-light)' }} />
              <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                <strong style={{ color: 'var(--accent-light)' }}>Security Note:</strong> X-Codes are cryptographically generated and cannot be guessed or brute-forced. Each code is validated server-side before granting exam access.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section section-border">
        <div className="container">
          <div ref={faqRef} className={`text-center reveal ${faqVisible ? 'visible' : ''}`} style={{ maxWidth: 640, margin: '0 auto 48px' }}>
            <span className="label">FAQ</span>
            <h2 className="heading-lg" style={{ marginTop: 12 }}>
              Frequently Asked <span className="gradient-text">Questions</span>
            </h2>
          </div>
          <div style={{ maxWidth: 700, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 16 }}>
            {faqs.map((faq) => (
              <div key={faq.q} className="card" style={{ padding: '24px 28px' }}>
                <h4 className="heading-sm" style={{ marginBottom: 8 }}>{faq.q}</h4>
                <p className="body-md">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section section-border">
        <div className="container">
          <div
            ref={ctaRef}
            className={`text-center reveal ${ctaVisible ? 'visible' : ''}`}
            style={{
              background: 'var(--bg-card)',
              borderRadius: 'var(--radius-xl)',
              padding: '64px 48px',
              position: 'relative',
              overflow: 'hidden',
              border: '1px solid var(--border)',
            }}
          >
            <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(circle at center, var(--accent-glow-strong) 0%, transparent 70%)', pointerEvents: 'none' }} />
            <div style={{ position: 'relative', zIndex: 1 }}>
              <h2 className="heading-lg">
                Ready to <span className="gradient-text">Get Started</span>?
              </h2>
              <p className="body-lg" style={{ marginTop: 12, maxWidth: 500, margin: '12px auto 32px' }}>
                Set up your institution and start conducting secure exams today
              </p>
              <div style={{ display: 'flex', gap: 12, justifyContent: 'center' }}>
                <Link to="/signup" className="btn btn-primary btn-lg">Create Account</Link>
                <Link to="/contact" className="btn btn-secondary btn-lg">Talk to Sales</Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
